spring:
  datasource:
    url: jdbc:mysql://10.4.8.2:20053/trade_center?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&useSSL=false&logger=com.mysql.jdbc.log.Slf4JLogger
    username: temp_admin
    password: temp_admin@2018
    driver-class-name: com.mysql.jdbc.Driver
